import { createContext, useContext, useEffect, useState, type ReactNode } from "react";

export type Lang = "fr" | "en";

// Dictionnaire centralisé. Ajoute une clé ici pour chaque nouveau texte,
// avec sa version fr ET en, puis utilise t("ma.cle") dans tes composants.
const dict = {
  nav: {
    explore: { fr: "Explorer", en: "Explore" },
    creators: { fr: "Créateurs", en: "Creators" },
    dashboard: { fr: "Dashboard", en: "Dashboard" },
    logout: { fr: "Déconnexion", en: "Log out" },
    login: { fr: "Connexion", en: "Log in" },
    signup: { fr: "Inscription", en: "Sign up" },
  },
  hero: {
    badge: { fr: "Le social shopping made for you", en: "Social shopping made for you" },
    titlePart1: { fr: "Trouve les pièces", en: "Find the pieces" },
    titlePart2: { fr: "de tes", en: "worn by your" },
    titlePart3: { fr: "créateurs", en: "creators" },
    steps: { fr: "Vidéo → références → achat en 1 clic", en: "Video → tags → shop in 1 click" },
    ctaExplore: { fr: "Explorer les looks", en: "Explore the looks" },
    ctaCreator: { fr: "Devenir créateur", en: "Become a creator" },
  },
  howItWorks: {
    title: { fr: "Comment ça marche", en: "How it works" },
    subtitle: { fr: "Trois étapes, zéro friction.", en: "Three steps, zero friction." },
    step1Title: { fr: "La vidéo", en: "The video" },
    step1Desc: { fr: "Le créateur poste sa tenue en vidéo sur TikTok, Instagram ou YouTube.", en: "The creator posts their outfit in a video on TikTok, Instagram or YouTube." },
    step2Title: { fr: "Les références", en: "The references" },
    step2Desc: { fr: "Chaque pièce portée est identifiée et listée sur la page du post.", en: "Every piece worn is identified and listed on the post page." },
    step3Title: { fr: "L'achat", en: "The purchase" },
    step3Desc: { fr: "Un clic sur la carte produit et tu es redirigé chez le vendeur.", en: "One click on the product card and you're redirected to the seller." },
  },
  popularCreators: {
    title: { fr: "Créateurs populaires", en: "Popular creators" },
    seeAll: { fr: "Voir tous", en: "See all" },
  },
  feed: {
    title: { fr: "Les derniers outfits", en: "Latest outfits" },
    subtitle: { fr: "Shop les looks de tes créateurs préférés.", en: "Shop the looks from your favorite creators." },
    empty: { fr: "Aucun post pour le moment.", en: "No posts yet." },
    watchVideo: { fr: "Voir la vidéo", en: "Watch video" },
  },
  creatorCta: {
    title1: { fr: "Deviens créateur,", en: "Become a creator," },
    title2: { fr: "monétise ton style", en: "monetize your style" },
    desc: { fr: "Rejoins Wanted Fashion, poste tes tenues, tague tes pièces et touche une commission sur chaque vente générée par ta communauté.", en: "Join Wanted Fashion, post your outfits, tag your pieces and earn a commission on every sale generated by your community." },
    cta: { fr: "Créer mon compte créateur", en: "Create my creator account" },
  },
  auth: {
    loginTitle: { fr: "Connexion", en: "Log in" },
    loginSubtitle: { fr: "Connecte-toi pour gérer tes posts.", en: "Log in to manage your posts." },
    email: { fr: "Email", en: "Email" },
    password: { fr: "Mot de passe", en: "Password" },
    loggingIn: { fr: "Connexion...", en: "Logging in..." },
    login: { fr: "Se connecter", en: "Log in" },
    noAccount: { fr: "Pas encore de compte ?", en: "Don't have an account yet?" },
    signupLink: { fr: "Inscris-toi", en: "Sign up" },
    invalidCreds: { fr: "Identifiants invalides", en: "Invalid credentials" },
    welcome: { fr: "Bienvenue !", en: "Welcome!" },
    signupTitle: { fr: "Inscription", en: "Sign up" },
    signupSubtitle: { fr: "Crée ton compte créateur Wanted Fashion.", en: "Create your Wanted Fashion creator account." },
    username: { fr: "Username", en: "Username" },
    usernamePlaceholder: { fr: "ton_username", en: "your_username" },
    creating: { fr: "Création...", en: "Creating..." },
    createAccount: { fr: "Créer mon compte", en: "Create my account" },
    alreadyAccount: { fr: "Déjà un compte ?", en: "Already have an account?" },
    loginLink: { fr: "Connecte-toi", en: "Log in" },
    invalidUsername: { fr: "Username invalide (3-30 caractères : lettres, chiffres, _ ou .)", en: "Invalid username (3-30 characters: letters, digits, _ or .)" },
    usernameTaken: { fr: "Ce username est déjà pris", en: "This username is already taken" },
    signupError: { fr: "Erreur lors de l'inscription", en: "Error during sign up" },
    profileFailed: { fr: "Compte créé mais profil échoué :", en: "Account created but profile failed:" },
    accountCreated: { fr: "Compte créé !", en: "Account created!" },
  },
  creatorPage: {
    home: { fr: "Accueil", en: "Home" },
    uploading: { fr: "Upload...", en: "Uploading..." },
    changeBanner: { fr: "Changer la bannière", en: "Change banner" },
    follow: { fr: "Suivre", en: "Follow" },
    posts: { fr: "Posts", en: "Posts" },
    productsTagged: { fr: "Produits taggés", en: "Tagged products" },
    shoppable: { fr: "Shoppable", en: "Shoppable" },
    allLooks: { fr: "100% des looks", en: "100% of the looks" },
    looksOf: { fr: "Les looks de", en: "Looks by" },
    notPublishedYet: { fr: "Ce créateur n'a pas encore publié.", en: "This creator hasn't posted yet." },
    watchVideo: { fr: "Voir la vidéo", en: "Watch video" },
    product: { fr: "produit", en: "product" },
    products: { fr: "produits", en: "products" },
    ctaTitle: { fr: "Toi aussi, partage tes tenues et gagne des commissions", en: "You too can share your outfits and earn commissions" },
    ctaButton: { fr: "Devenir créateur", en: "Become a creator" },
    notFound: { fr: "Créateur introuvable.", en: "Creator not found." },
    uploadError: { fr: "Erreur upload", en: "Upload error" },
    saveError: { fr: "Erreur sauvegarde", en: "Save error" },
    avatarUpdated: { fr: "Photo de profil mise à jour !", en: "Profile picture updated!" },
    bannerUpdated: { fr: "Bannière mise à jour !", en: "Banner updated!" },
  },
  postPage: {
    notFound: { fr: "Post introuvable.", en: "Post not found." },
    watchVideo: { fr: "Voir la vidéo", en: "Watch video" },
    backToFeed: { fr: "Retour au feed", en: "Back to feed" },
    pieceSingular: { fr: "pièce", en: "piece" },
    piecePlural: { fr: "pièces", en: "pieces" },
    identifiedSingular: { fr: "identifiée", en: "identified" },
    identifiedPlural: { fr: "identifiées", en: "identified" },
    inThisVideo: { fr: "dans cette vidéo — clique sur une carte pour acheter.", en: "in this video — click a card to shop." },
    noProduct: { fr: "Aucun produit ajouté.", en: "No product added." },
    wantMoreLooks: { fr: "Envie de shopper plus de looks ?", en: "Want to shop more looks?" },
    seeFeed: { fr: "Voir le feed", en: "See the feed" },
    seeProfile: { fr: "Voir le profil", en: "See profile" },
  },
  dashboard: {
    myPosts: { fr: "Mes posts", en: "My posts" },
    manageOutfits: { fr: "Gère tes outfits Wanted Fashion.", en: "Manage your Wanted Fashion outfits." },
    settings: { fr: "Paramètres", en: "Settings" },
    newPost: { fr: "+ Nouveau post", en: "+ New post" },
    noPostYet: { fr: "Aucun post pour le moment.", en: "No posts yet." },
    createFirstPost: { fr: "Créer mon premier post", en: "Create my first post" },
    product: { fr: "produit", en: "product" },
    products: { fr: "produits", en: "products" },
    preview: { fr: "Aperçu", en: "Preview" },
    edit: { fr: "Éditer", en: "Edit" },
    copyUrl: { fr: "Copier URL", en: "Copy URL" },
    urlCopied: { fr: "URL copiée", en: "URL copied" },
    delete: { fr: "Supprimer", en: "Delete" },
    deletePostTitle: { fr: "Supprimer ce post ?", en: "Delete this post?" },
    deletePostDesc: { fr: "Cette action est définitive.", en: "This action is permanent." },
    cancel: { fr: "Annuler", en: "Cancel" },
    postDeleted: { fr: "Post supprimé", en: "Post deleted" },
  },
  settings: {
    title: { fr: "Paramètres", en: "Settings" },
    profilePicture: { fr: "Photo de profil", en: "Profile picture" },
    uploading: { fr: "Upload...", en: "Uploading..." },
    choosePicture: { fr: "Choisir une photo", en: "Choose a picture" },
    banner: { fr: "Bannière", en: "Banner" },
    chooseBanner: { fr: "Choisir une bannière", en: "Choose a banner" },
    username: { fr: "Username", en: "Username" },
    bio: { fr: "Bio", en: "Bio" },
    bioPlaceholder: { fr: "Parle-toi en quelques mots...", en: "Tell us about yourself..." },
    saving: { fr: "Sauvegarde...", en: "Saving..." },
    save: { fr: "Sauvegarder", en: "Save" },
    uploadPhotoError: { fr: "Erreur upload photo", en: "Photo upload error" },
    photoUploaded: { fr: "Photo chargée !", en: "Photo uploaded!" },
    uploadBannerError: { fr: "Erreur upload bannière", en: "Banner upload error" },
    bannerUploaded: { fr: "Bannière chargée !", en: "Banner uploaded!" },
    invalidUsername: { fr: "Username invalide (3-30 caractères : lettres, chiffres, _ ou .)", en: "Invalid username (3-30 characters: letters, digits, _ or .)" },
    settingsSaved: { fr: "Paramètres enregistrés !", en: "Settings saved!" },
  },
  postForm: {
    thePost: { fr: "Le post", en: "The post" },
    titleLabel: { fr: "Titre *", en: "Title *" },
    tiktokUrlLabel: { fr: "URL TikTok ou Instagram", en: "TikTok or Instagram URL" },
    tiktokUrlHint: { fr: "Colle l'URL TikTok ou Instagram : la miniature se remplit automatiquement.", en: "Paste the TikTok or Instagram URL: the thumbnail fills in automatically." },
    coverImageLabel: { fr: "URL image de couverture", en: "Cover image URL" },
    importPhoto: { fr: "Importer une photo", en: "Import a photo" },
    productsCount: { fr: "Produits", en: "Products" },
    addProduct: { fr: "+ Ajouter un produit", en: "+ Add a product" },
    noProduct: { fr: "Aucun produit. Clique sur \"Ajouter un produit\".", en: "No product. Click \"Add a product\"." },
    productN: { fr: "Produit", en: "Product" },
    remove: { fr: "Retirer", en: "Remove" },
    buyLink: { fr: "Lien d'achat *", en: "Buy link *" },
    buyLinkHint: { fr: "Colle l'URL produit : nom, image et prix se remplissent automatiquement.", en: "Paste the product URL: name, image and price fill in automatically." },
    name: { fr: "Nom *", en: "Name *" },
    price: { fr: "Prix", en: "Price" },
    imageUrl: { fr: "URL image", en: "Image URL" },
    brand: { fr: "Marque", en: "Brand" },
    saving: { fr: "Sauvegarde...", en: "Saving..." },
    uploadPhotoFailed: { fr: "Échec de l'import de la photo. Réessaie ou colle une URL d'image manuellement.", en: "Photo import failed. Try again or paste an image URL manually." },
    tiktokThumbFail: { fr: "La miniature automatique ne marche que pour les vraies vidéos TikTok. Pour un post en slide (photos), importe une photo directement pour l'image de couverture.", en: "The automatic thumbnail only works for real TikTok videos. For a slide post (photos), import a photo directly for the cover image." },
    instagramThumbFail: { fr: "Impossible de récupérer automatiquement l'image de ce post Instagram. Importe une photo directement pour l'image de couverture.", en: "Couldn't automatically retrieve the image for this Instagram post. Import a photo directly for the cover image." },
  },
  newPost: {
    title: { fr: "Nouveau post", en: "New post" },
    publish: { fr: "Publier", en: "Publish" },
    creatorProfileNotFound: { fr: "Profil créateur introuvable", en: "Creator profile not found" },
    genericError: { fr: "Erreur", en: "Error" },
    postCreatedProductsFailed: { fr: "Post créé mais produits échoués :", en: "Post created but products failed:" },
    postPublished: { fr: "Post publié !", en: "Post published!" },
  },
  editPost: {
    title: { fr: "Éditer le post", en: "Edit post" },
    save: { fr: "Sauvegarder", en: "Save" },
    postNotFound: { fr: "Post introuvable.", en: "Post not found." },
    postUpdated: { fr: "Post mis à jour", en: "Post updated" },
  },
  root: {
    notFoundTitle: { fr: "Page introuvable.", en: "Page not found." },
    backHome: { fr: "Retour à l'accueil", en: "Back to home" },
    errorTitle: { fr: "Une erreur est survenue", en: "Something went wrong" },
    errorDesc: { fr: "Quelque chose s'est mal passé. Réessaie ou retourne à l'accueil.", en: "Something went wrong. Try again or go back home." },
    retry: { fr: "Réessayer", en: "Try again" },
    home: { fr: "Accueil", en: "Home" },
  },
} as const;

type Dict = typeof dict;
type SectionKey = keyof Dict;
type FlatKey = { [S in SectionKey]: `${S}.${Extract<keyof Dict[S], string>}` }[SectionKey];

interface LanguageContextValue {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: FlatKey) => string;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

const STORAGE_KEY = "wf-lang";

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>("fr");

  useEffect(() => {
    const stored = typeof window !== "undefined" ? (localStorage.getItem(STORAGE_KEY) as Lang | null) : null;
    if (stored === "fr" || stored === "en") {
      setLangState(stored);
    } else if (typeof navigator !== "undefined" && navigator.language?.toLowerCase().startsWith("en")) {
      setLangState("en");
    }
  }, []);

  const setLang = (l: Lang) => {
    setLangState(l);
    if (typeof window !== "undefined") localStorage.setItem(STORAGE_KEY, l);
  };

  const t = (key: FlatKey): string => {
    const [section, entry] = key.split(".") as [SectionKey, string];
    const node = (dict as any)[section]?.[entry];
    if (!node) return key;
    return node[lang] ?? node.fr;
  };

  return <LanguageContext.Provider value={{ lang, setLang, t }}>{children}</LanguageContext.Provider>;
}

export function useTranslation() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useTranslation doit être utilisé dans un LanguageProvider");
  return ctx;
}
