import { createContext, useContext, useEffect, useState, type ReactNode } from "react";

export type Lang = "fr" | "en";

// Dictionnaire centralisé. Ajoute une clé ici pour chaque nouveau texte,
// avec sa version fr ET en, puis utilise t("ma.cle") dans tes composants.
const dict = {
  nav: {
    explore: { fr: "Explorer", en: "Explore" },
    creators: { fr: "Créateurs", en: "Creators" },
    dashboard: { fr: "Dashboard", en: "Dashboard" },
    logout: { fr: "Déconnexion", en: "Log out" },
    login: { fr: "Connexion", en: "Log in" },
    signup: { fr: "Inscription", en: "Sign up" },
  },
  hero: {
    badge: { fr: "Le social shopping made for you", en: "Social shopping made for you" },
    titlePart1: { fr: "Trouve les pièces", en: "Find the pieces" },
    titlePart2: { fr: "de tes", en: "worn by your" },
    titlePart3: { fr: "créateurs", en: "creators" },
    steps: { fr: "Vidéo → références → achat en 1 clic", en: "Video → tags → shop in 1 click" },
    ctaExplore: { fr: "Explorer les looks", en: "Explore the looks" },
    ctaCreator: { fr: "Devenir créateur", en: "Become a creator" },
  },
  howItWorks: {
    title: { fr: "Comment ça marche", en: "How it works" },
    subtitle: { fr: "Trois étapes, zéro friction.", en: "Three steps, zero friction." },
    step1Title: { fr: "La vidéo", en: "The video" },
    step1Desc: { fr: "Le créateur poste sa tenue en vidéo sur TikTok, Instagram ou YouTube.", en: "The creator posts their outfit in a video on TikTok, Instagram or YouTube." },
    step2Title: { fr: "Les références", en: "The references" },
    step2Desc: { fr: "Chaque pièce portée est identifiée et listée sur la page du post.", en: "Every piece worn is identified and listed on the post page." },
    step3Title: { fr: "L'achat", en: "The purchase" },
    step3Desc: { fr: "Un clic sur la carte produit et tu es redirigé chez le vendeur.", en: "One click on the product card and you're redirected to the seller." },
  },
  popularCreators: {
    title: { fr: "Créateurs populaires", en: "Popular creators" },
    seeAll: { fr: "Voir tous", en: "See all" },
  },
  feed: {
    title: { fr: "Les derniers outfits", en: "Latest outfits" },
    subtitle: { fr: "Shop les looks de tes créateurs préférés.", en: "Shop the looks from your favorite creators." },
    empty: { fr: "Aucun post pour le moment.", en: "No posts yet." },
    watchVideo: { fr: "Voir la vidéo", en: "Watch video" },
  },
  creatorCta: {
    title1: { fr: "Deviens créateur,", en: "Become a creator," },
    title2: { fr: "monétise ton style", en: "monetize your style" },
    desc: { fr: "Rejoins Wanted Fashion, poste tes tenues, tague tes pièces et touche une commission sur chaque vente générée par ta communauté.", en: "Join Wanted Fashion, post your outfits, tag your pieces and earn a commission on every sale generated by your community." },
    cta: { fr: "Créer mon compte créateur", en: "Create my creator account" },
  },
} as const;

type Dict = typeof dict;
type SectionKey = keyof Dict;
type FlatKey = { [S in SectionKey]: `${S}.${Extract<keyof Dict[S], string>}` }[SectionKey];

interface LanguageContextValue {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: FlatKey) => string;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

const STORAGE_KEY = "wf-lang";

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>("fr");

  useEffect(() => {
    const stored = typeof window !== "undefined" ? (localStorage.getItem(STORAGE_KEY) as Lang | null) : null;
    if (stored === "fr" || stored === "en") {
      setLangState(stored);
    } else if (typeof navigator !== "undefined" && navigator.language?.toLowerCase().startsWith("en")) {
      setLangState("en");
    }
  }, []);

  const setLang = (l: Lang) => {
    setLangState(l);
    if (typeof window !== "undefined") localStorage.setItem(STORAGE_KEY, l);
  };

  const t = (key: FlatKey): string => {
    const [section, entry] = key.split(".") as [SectionKey, string];
    const node = (dict as any)[section]?.[entry];
    if (!node) return key;
    return node[lang] ?? node.fr;
  };

  return <LanguageContext.Provider value={{ lang, setLang, t }}>{children}</LanguageContext.Provider>;
}

export function useTranslation() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useTranslation doit être utilisé dans un LanguageProvider");
  return ctx;
}
